version: '3.8'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev","--import-realm" ]
    volumes:
      - keycloak_reamls_data:/opt/keycloak/data/
      - ./deploy:/opt/keycloak/standalone/deployments
    networks:
      - keycloak-net

volumes:
  keycloak_reamls_data:
    external: false

networks:
  keycloak-net:
    driver: bridge

#version: '2'
#services:
#  postgresql:
#    image: docker.io/bitnami/postgresql:latest
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - POSTGRESQL_USERNAME=bn_keycloak
#      - POSTGRESQL_DATABASE=bitnami_keycloak
#    volumes:
#      - 'postgresql_data:/bitnami/postgresql'
#  keycloak:
#    image: docker.io/bitnami/keycloak:11.0.3
#    ports:
#      - "8080:8080"
#    environment:
#      KEYCLOAK_CREATE_ADMIN_USER: true
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    depends_on:
#      - postgresql
#volumes:
#  postgresql_data:
#    driver: local